services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_ipz4
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: postgres_ipz4
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  # api:
  #   container_name: ipz4_api
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - POSTGRES_URL=${POSTGRES_URL}
  #     - MONGO_URI=${MONGO_URI}
  #   depends_on:
  #     - mongodb
  #     - postgres

volumes:
  mongo_data:
  postgres_data: